# Generated by Django 4.1.6 on 2023-02-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.CharField(choices=[('Ropa', 'Ropa'), ('Tecnologia', 'Tecnologia'), ('Computacion', 'Computacion'), ('Deportes', 'Deportes'), ('Electrodomesticos', 'Electrodomesticos'), ('Instrumentos', 'Instrumentos')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='type',
            field=models.CharField(choices=[('Zapatillas', 'Zapatillas'), ('Remeras', 'Remeras'), ('Pantalones', 'Pantalones'), ('Camperas', 'Camperas'), ('Gorras', 'Gorras')], default='', max_length=40),
        ),
    ]
