# Generated by Django 4.1.6 on 2023-02-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productmodel_category_alter_productmodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='type',
        ),
    ]
