# Generated by Django 4.1.6 on 2023-02-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_productmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(choices=[('Ropa', 'Ropa'), ('Muebles', 'Muebles'), ('Computacion', 'Computacion'), ('Deportes', 'Deportes'), ('Electrodomesticos', 'Electrodomesticos'), ('Instrumentos', 'Instrumentos')], default='', max_length=40),
        ),
    ]
