# Generated by Django 4.1.6 on 2023-02-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='type',
            field=models.CharField(choices=[('Zapatillas', 'Zapatillas'), ('Camisetas', 'Camisetas'), ('Pantalones', 'Pantalones'), ('Abrigos', 'Abrigos'), ('Gorras', 'Gorras')], default='', max_length=40),
        ),
    ]
