# Generated by Django 4.1.6 on 2023-02-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customusermodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
