# Generated by Django 4.1.6 on 2023-03-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_customusermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/drifqbdtu/image/upload/v1678034948/ecommer/images/user_sfttie.png', upload_to='./images'),
        ),
    ]
